name: Exploring envirnment variables

on: push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: szgyuval123
    IMAGE_NAME: actions
    
jobs:
    build_image:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build        
          run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

        - name: Docker login
          env:
            DOCKER_PASSWORD: Yuval200r
          run: echo docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

        - name: Docker publish
          run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
            
    deploy:
        needs: build_image
        runs-on: ubuntu-latest
        steps:
        - name: Docker run
          run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest 
