name: Generate ASCCI Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v5
        
        - name: list files
          run: ls -ltar
            
        - name: Excuting Shell Script
          run: ./ascii-script.sh